app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
$domain = Request::getHost();

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::group(['middleware' => ['web']], function () use($domain)
{
    if ($domain != Config::get('app.domain'))
    {
        Route::group(['domain'=> $domain, 'namespace'=>'Sites', 'as'=>"sites.", "middleware"=>["domain"]], function()
        {
            Route::group(['prefix'=> 'admin', 'namespace'=>'Admin'], function()
            {

            });

            Route::get("/", ["as"=>"home.index", "uses"=>"HomeController@index"]);
            Route::get('{pages}', [ 'as' => 'pages.show', 'uses'=>'PagesController@show'])->where('pages', '(.*)');
            Route::resource('pages', "PagesController");
            //Route::get('/', ['as'=>'home', 'uses' => 'PagesController@home']);
        });
    }
    elseif($domain == Config::get('app.domain'))
    {
        Route::group(['domain'=> Config::get('app.domain')], function()
        {
            Route::group(['middleware'=>'auth'], function()
            {
                Route::resource('sites', 'SitesController');
                Route::get('/dashboard', ['as'=>'dashboard', 'uses'=>"AdminController@index"]);
            });

            Route::get('/', ['as'=>'home', 'uses' => 'HomeController@index']);
            Route::get('about-us', ['as'=>'about-us', 'uses'=>'PagesController@aboutUs']);
            Route::auth();
            Route::resource('themes', 'ThemesController');


        });
    }
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Plan;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function __construct()
    {
        $this->middleware("guest");
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $plans = Plan::with(['features'])->get();
        return view('home.index', compact('plans'));
    }
}

app/Http/Controllers/Sites/HomeController.php
<?php

namespace App\Http\Controllers\Sites;

use App\Page;
use App\Site;
use igaster\laravelTheme\Theme;
use igaster\laravelTheme\Themes;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index(Request $request)
    {
        $host = $request->getHost();
        $site = Site::with([])->currentHost($host)->first();
        $theme = $site->theme->name;
        $themes = new Themes();
        $themes->set($theme);

        $connection = explode('.', $host);
        $page = new Page();
        $page->setConnection($connection[0]);
        $pages = $page->all();


        return view('home.index');
        /*
        $page = new Page();
        $page->setConnection()

        return view('home.index');*/
    }
}

resources/views/home/dashboard.blade.php
@extends('layouts.master')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="page-header">
                    <h1>Dashboard</h1>
                </div>
            </div>
        </div>
        @if($sites)
        <div class="row">
            <div class="col-sm-12">
               <div class="panel panel-default">
                   <div class="panel-heading">
                       <h2 class="panel-title">My Sites</h2>
                   </div>
                   <div class="panel-body">
                       <table class="table">
                           <thead>
                           <tr>
                               <th>Domain</th>
                               <th>Action</th>
                           </tr>
                           </thead>
                           <tbody>
                           @foreach($sites as $site)
                           <tr>
                               <td>{{ $site->domain }}</td>
                               <td><a href="http://{{ $site->domain }}" target="_blank">View site</a></td>
                           </tr>
                           @endforeach
                           </tbody>
                       </table>
                   </div>
               </div>
            </div>
        </div>
        @else
        <div class="row">
            <div class="col-sm-12">
                <form action="{{ route('sites.store') }}" method="post">
                    {{ csrf_field() }}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">Select a theme</h3>
                        </div>
                        <div class="panel-body">
                            @foreach($themes as $theme)
                                <div class="col-sm-6 col-md-4">
                                    <div class="thumbnail">
                                        <img src="{{ $theme->thumbnail }}" alt="{{ $theme->name }}">
                                        <div class="caption">
                                            <div class="radio">
                                                <label>
                                                    <input type="radio" name="theme_id" id="theme-{{ $theme->id }}" value="{{ $theme->id }}" checked>
                                                    {{ $theme->name }}
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h2 class="panel-title">Create a site</h2>
                        </div>
                        <div class="panel-body">

                            <div></div>
                            <div class="form-group form-group-lg">
                                <label>Domain</label>
                                <input type="text" name="domain" class="form-control" value="" />
                            </div>

                        </div>
                        <div class="panel-footer">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        @endif
    </div>
    {{--
     Newest theme showed
     Create sites
     News from formastudios
    --}}
@stop

resources/views/home/index.blade.php
@extends('layouts.master')
@section("slide.show")
    <div class="slider-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="slider-group">
                        <div class="slider">
                            <h1 class="slider-featured-text">
                                We build, and we <span style="font-weight: normal">know how <br /> to create</span>  <span style="color:#1abc9c">great</span> websites...
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('content')
    <section id="subscription">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="text-center">Select a plan</h2>
                </div>
            </div>
            <div class="row pricetable-container">
                @foreach($plans as $plan)
                    <div class="col-md-4 price-table">
                        <h3>{{ $plan->braintree_plan }}</h3>
                        <p>{{ money_format('%i', $plan->price) }} <span>Per month</span></p>
                        <ul>
                            @foreach($plan->features as $feature)
                            <li>{{ $feature->title }}</li>
                            @endforeach
                        </ul>
                        <a href="/register/?plan={{ str_slug($plan->braintree_plan) }}" class="btn btn-primary">Subscribe</a>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
@stop